### ISSUE TITLE
Protocol version error

### ISSUE THREAD

**Issue by dipenpatel235** [SUPLA/supla-espressif-esp#17]
I have compile code of sonoff_ds18b20

and getting below result

connected with Xiaomi_C734, channel 6
dhcp client start...
ip:192.168.1.217,mask:255.255.255.0,gw:192.168.1.1
WiFi Status: 5
IP Received
Resolv my.hostname.com
client handshake start.
client handshake ok!
Protocol version error
state: 5 -> 0 (0)
rm 0
Disconnected
WiFi Status: 1
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 5
cnt

**Comment by przemyslawzygmunt** [comment]
Do not use the development version.
Use some release
https://github.com/SUPLA/supla-espressif-esp/releases

**Comment by dipenpatel235** [comment]
i got this error when i am tryimg to build the sonoff_ds18b20 code  in your release code v2.5

cp: cannot stat './ld/sdk154/1024_eagle.appl.v6.ld':No such file or directory

**Comment by przemyslawzygmunt** [comment]
OK. You can use development version of the source code but then you should add:
#define ESP8266_SUPLA_PROTO VERSION 7
to your header file of the board definition

**Comment by dipenpatel235** [comment]
ok

**Comment by dipenpatel235** [comment]
Worked..

Thanks
