### ISSUE TITLE
Add the ability to reset the device identifier (GUID)

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-espressif-esp#42]

**Comment by ermaya** [comment]
In my latest compilations I use the supla server section in wificonfig to generate a new Guid and Autkey.
typing "get_new_guid_and_authkey" and pressing save renews both.
![new guid](https://user-images.githubusercontent.com/34374601/71887567-ae496380-313e-11ea-9b84-9922a1fb8a43.png)
In my opinion it would be easy to add.

**Comment by przemyslawzygmunt** [comment]
https://github.com/SUPLA/supla-core/issues/156

**Comment by przemyslawzygmunt** [comment]
We change the scope of the device's uniqueness from server to user.
